version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql2019_dicri
    hostname: sql2019_dicri
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - dicri_net
    volumes:
      - ./db:/var/opt/mssql

  backend:
    build: .
    container_name: dicri_backend
    ports:
      - "3001:3001"
    environment:
      DB_SERVER: sql2019_dicri
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}

      GOOGLE_APPLICATION_CREDENTIALS: "/app/src/config/google-service-account.json"
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}

    depends_on:
      - sqlserver
    networks:
      - dicri_net
    volumes:
      - ./src/config/google-service-account.json:/app/src/config/google-service-account.json

networks:
  dicri_net:
    name: dicri_net
